In [2]:
import pandas as pd

In [87]:
# Read data from file
df = pd.read_csv('adult.data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  salary          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [88]:
# How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.
race_count = df['race'].value_counts()
race_count

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [103]:
# What is the average age of men?
average_age_men = df.loc[df['sex'] == 'Male', 'age'].mean().round(1)
average_age_men

np.float64(39.4)

In [104]:
# What is the percentage of people who have a Bachelor's degree?
percentage_bachelors = round(df[df['education'] == 'Bachelors'].shape[0] / df.shape[0] * 100, 1)
percentage_bachelors

16.4

In [91]:
df[['education', 'education-num']]

        education  education-num
0       Bachelors             13
1       Bachelors             13
2         HS-grad              9
3            11th              7
4       Bachelors             13
...           ...            ...
32556  Assoc-acdm             12
32557     HS-grad              9
32558     HS-grad              9
32559     HS-grad              9
32560     HS-grad              9

[32561 rows x 2 columns]

In [92]:
df.loc[df['education-num'] >= 13, ['education', 'education-num']]

         education  education-num
0        Bachelors             13
1        Bachelors             13
4        Bachelors             13
5          Masters             14
8          Masters             14
...            ...            ...
32539    Doctorate             16
32544      Masters             14
32548  Prof-school             15
32553      Masters             14
32554      Masters             14

[8067 rows x 2 columns]

In [101]:
df['salary'].unique()

array(['<=50K', '>50K'], dtype=object)

In [128]:
# What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?
# What percentage of people without advanced education make more than 50K?

# with and without `Bachelors`, `Masters`, or `Doctorate`
higher_education = df[df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])]
lower_education = df[~df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])]

# percentage with salary >50K
higher_education_rich = round((higher_education['salary'] == '>50K').sum() / higher_education.shape[0] * 100, 1)
lower_education_rich = round((lower_education['salary'] == '>50K').sum() / lower_education.shape[0] * 100, 1)

lower_education_rich

np.float64(17.4)

In [112]:
df['hours-per-week'].unique()

array([40, 13, 16, 45, 50, 80, 30, 35, 60, 20, 52, 44, 15, 25, 38, 43, 55,
       48, 58, 32, 70,  2, 22, 56, 41, 28, 36, 24, 46, 42, 12, 65,  1, 10,
       34, 75, 98, 33, 54,  8,  6, 64, 19, 18, 72,  5,  9, 47, 37, 21, 26,
       14,  4, 59,  7, 99, 53, 39, 62, 57, 78, 90, 66, 11, 49, 84,  3, 17,
       68, 27, 85, 31, 51, 77, 63, 23, 87, 88, 73, 89, 97, 94, 29, 96, 67,
       82, 86, 91, 81, 76, 92, 61, 74, 95])

In [114]:
# What is the minimum number of hours a person works per week (hours-per-week feature)?
min_work_hours = df['hours-per-week'].min()
min_work_hours

1

In [173]:
# What percentage of the people who work the minimum number of hours per week have a salary of >50K?
num_min_workers = df.loc[(df['hours-per-week'] == min_work_hours) & (df['salary'] == '>50K')].shape[0]

rich_percentage = round(num_min_workers / df.loc[(df['hours-per-week'] == min_work_hours)].shape[0] * 100, 1)

# What country has the highest percentage of people that earn >50K?
highest_earning_country = (df[df['salary'] == '>50K']['native-country'].value_counts() / df['native-country'].value_counts() * 100).idxmax()
highest_earning_country_percentage = round(df[df['salary'] == '>50K']['native-country'].value_counts() / df['native-country'].value_counts() * 100, 1).max()

# Identify the most popular occupation for those who earn >50K in India.
top_IN_occupation = df[(df['salary'] == '>50K') & (df['native-country'] == 'India')]['occupation'].value_counts().idxmax()

'Prof-specialty'